int _putchar(int n);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char * src, unsigned int n);
char *_strchr(char *, char c);
unsigned int _strspn(char *a, char *b);
char *_strpbrk(char *a, char *b);
char *_strstr(char *a, char *b);
void print_chessboard(char (*a)[8]);
void print_diagsums(int *a, intb);
void set_string(char **s, char *to);
