int _putchar(int n);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char * src, unsigned int n);
char *_strchr(char *, char c);
unsigned int _strspn(char *, char *);
char *_strpbrk(char *, char *);
char *_strstr(char *, char *);
void print_chessboard(char (*a)[8]);
void print_diagsums(int *, int);
void set_string(char **s, char *to);
